{% set name = "owa" %}
{% set version = "0.4.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/owa-{{ version }}.tar.gz
  sha256: f2b0fd15b2c32dcd3add08e85d028b466fe38b7605891cb872cb1e37f05436a4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mcap-owa-support
    - ocap
    - owa-cli
    - owa-core
    - owa-env-desktop
    - owa-env-gst
    - owa-msgs

test:
  imports:
    - owa
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/open-world-agents/open-world-agents
  summary: Everything you need to build state-of-the-art foundation multimodal desktop agent, end-to-end.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
